In [1]:
import pandas as pd

# Read Quantitative Data

In [2]:
df = pd.read_csv('cleaned_data/quant_features.csv')
df.head()

,community,shape_area,area_num_1,shape_len,2000_POP,2010_POP,TOT_POP,UND19,A20_34,A35_49,...,Childhood Lead Poisoning,Gonorrhea in Females,Tuberculosis,Below Poverty Level,Crowded Housing,Dependency,No High School Diploma,Per Capita Income,Unemployment,OV65
0,DOUGLAS,46004621.16,35,31027.05451,26470,18238,20781,0.212309,0.310813,0.172465,...,0.000,10.633,0.042,0.261,0.016,0.310,0.169,23098,0.167,0.144411
1,OAKLAND,16913961.04,36,19565.50615,6110,5918,6645,0.333333,0.184349,0.233860,...,0.003,16.554,0.067,0.381,0.035,0.405,0.176,19312,0.266,0.098721
2,FULLER PARK,19916704.87,37,25339.08975,3420,2876,2439,0.161132,0.193522,0.148421,...,0.025,10.619,0.000,0.555,0.045,0.382,0.337,9016,0.400,0.260763
3,GRAND BOULEVARD,48492503.16,38,28196.83716,28006,21929,22313,0.264823,0.193251,0.216959,...,0.010,14.546,0.132,0.283,0.027,0.417,0.194,22056,0.206,0.146193
4,KENWOOD,29071741.93,39,23325.16791,18363,17841,17189,0.184420,0.275816,0.184886,...,0.004,6.102,0.000,0.231,0.023,0.342,0.108,37519,0.110,0.177265

In [3]:
df.shape

(77, 111)

# Read Qualitative Data

In [4]:
df2 = pd.read_csv('cleaned_data/airbnb.csv')
df2.head()

,neighborhood_id,accessible,activities,african,airport,amazing,american,aquarium,architecture,art,...,wine,winning,wonderful,work,working,world,young,zoo,num_listings,price_norm
0,Albany Park,0.042857,0.0,0.014286,0.071429,0.057143,0.057143,0.0,0.014286,0.014286,...,0.071429,0.0,0.0,0.0,0.000000,0.071429,0.014286,0.0,94,28.490166
1,Archer Heights,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,6,50.786111
2,Armour Square,0.017241,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.103448,...,0.000000,0.0,0.0,0.0,0.000000,0.051724,0.000000,0.0,97,28.169723
3,Ashburn,0.000000,0.0,0.000000,0.555556,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.111111,0.000000,0.000000,0.0,11,20.187879
4,Auburn Gresham,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.083333,0.000000,0.000000,0.0,15,25.796667

In [11]:
df2.neighborhood_id = df2.neighborhood_id.str.upper()
df2.head()

,neighborhood_id,accessible,activities,african,airport,amazing,american,aquarium,architecture,art,...,wine,winning,wonderful,work,working,world,young,zoo,num_listings,price_norm
0,ALBANY PARK,0.042857,0.0,0.014286,0.071429,0.057143,0.057143,0.0,0.014286,0.014286,...,0.071429,0.0,0.0,0.0,0.000000,0.071429,0.014286,0.0,94,28.490166
1,ARCHER HEIGHTS,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,6,50.786111
2,ARMOUR SQUARE,0.017241,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.103448,...,0.000000,0.0,0.0,0.0,0.000000,0.051724,0.000000,0.0,97,28.169723
3,ASHBURN,0.000000,0.0,0.000000,0.555556,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.111111,0.000000,0.000000,0.0,11,20.187879
4,AUBURN GRESHAM,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.0,0.0,0.083333,0.000000,0.000000,0.0,15,25.796667

In [5]:
df2.shape

(73, 290)

In [6]:
df3 = pd.read_csv('cleaned_data/foursquare.csv')
df3.head()

,Neighborhood,ATM,Accessories Store,Adult Boutique,Afghan Restaurant,African Restaurant,Airport,Airport Food Court,Airport Lounge,Airport Service,...,Volleyball Court,Warehouse,Warehouse Store,Waterfront,Whisky Bar,Wine Bar,Wine Shop,Wings Joint,Women's Store,Yoga Studio
0,ALBANY PARK,0.0,0.0,0.0,0.01,0.00,0.00,0.00,0.0,0.00,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.01,0.0,0.0
1,ARCHER HEIGHTS,0.0,0.0,0.0,0.00,0.00,0.01,0.01,0.0,0.01,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.01,0.0,0.0
2,ARMOUR SQUARE,0.0,0.0,0.0,0.00,0.01,0.00,0.00,0.0,0.00,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.02,0.0,0.0
3,ASHBURN,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00,...,0.0,0.0,0.02,0.0,0.0,0.0,0.0,0.00,0.0,0.0
4,AUBURN GRESHAM,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.00,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.01,0.0,0.0

# Merge Datasets on Unique Identifier

In [12]:
merged = pd.merge(df,df2,left_on='community', right_on = 'neighborhood_id')
merged = pd.merge(merged,df3,left_on='neighborhood_id', right_on = 'Neighborhood')
merged.head()

,community_x,shape_area,area_num_1,shape_len,2000_POP,2010_POP,TOT_POP,UND19,A20_34,A35_49,...,Volleyball Court,Warehouse,Warehouse Store,Waterfront,Whisky Bar,Wine Bar,Wine Shop,Wings Joint,Women's Store,Yoga Studio
0,DOUGLAS,46004621.16,35,31027.05451,26470,18238,20781,0.212309,0.310813,0.172465,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.020833,0.0,0.00
1,OAKLAND,16913961.04,36,19565.50615,6110,5918,6645,0.333333,0.184349,0.233860,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.010000,0.0,0.00
2,FULLER PARK,19916704.87,37,25339.08975,3420,2876,2439,0.161132,0.193522,0.148421,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.020000,0.0,0.00
3,GRAND BOULEVARD,48492503.16,38,28196.83716,28006,21929,22313,0.264823,0.193251,0.216959,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.010000,0.0,0.00
4,KENWOOD,29071741.93,39,23325.16791,18363,17841,17189,0.184420,0.275816,0.184886,...,0.0,0.0,0.0,0.01,0.0,0.0,0.0,0.000000,0.0,0.02

In [13]:
merged.shape

(73, 724)

# Drop Duplicate Column and Split Qualitative/Quantitative Features

In [14]:
print(merged.columns.tolist())

['community_x', 'shape_area', 'area_num_1', 'shape_len', '2000_POP', '2010_POP', 'TOT_POP', 'UND19', 'A20_34', 'A35_49', 'A50_64', 'A65_74', 'A75_84', 'OV85', 'MED_AGE', 'WHITE', 'HISP', 'BLACK', 'ASIAN', 'OTHER', 'POP_16OV', 'IN_LBFRC', 'EMP', 'UNEMP', 'NOT_IN_LBFRC', 'WORK_AT_HOME', 'TOT_COMM', 'POP_25OV', 'LT_HS', 'HS', 'SOME_COLL', 'ASSOC', 'BACH', 'GRAD_PROF', 'INC_LT_25K', 'INC_25_50K', 'INC_50_75K', 'INC_75_100K', 'INC_100_150K', 'INC_GT_150', 'MEDINC', 'TOT_HH', 'OWN_OCC_HU', 'RENT_OCC_HU', 'VAC_HU', 'HU_TOT', 'HV_LT_150K', 'HV_150_300K', 'HV_300_500K', 'HV_GT_500K', 'MED_HV', 'AVG_VMT', 'OPEN_SPACE_PER_1000', 'Sfperc', 'Mfperc', 'MIXperc', 'COMMperc', 'INSTperc', 'INDperc', 'TRANSperc', 'Agperc', 'OPENperc', 'VACperc', 'NATIVE', 'FOR_BORN', 'POP_OV5', 'ONLY_ENGLISH', 'NOT_ENGLISH', 'LING_ISO', 'ENGLISH', 'SPANISH', 'SLAVIC', 'CHINESE', 'TAGALOG', 'ARABIC', 'KOREAN', 'OTHER_ASIAN', 'OTHER_EURO', 'OTHER_UNSPEC', 'highly_walkable_pop_pct', 'highly_walkable_emp_pct', 'assoc_plus_pct', 'in_lbr_frc_pct', 'PopDens', 'Birth Rate', 'General Fertility Rate', 'Low Birth Weight', 'Prenatal Care Beginning in First Trimester', 'Preterm Births', 'Teen Birth Rate', 'Assault (Homicide)', 'Breast cancer in females', 'Cancer (All Sites)', 'Colorectal Cancer', 'Diabetes-related', 'Firearm-related', 'Infant Mortality Rate', 'Lung Cancer', 'Prostate Cancer in Males', 'Stroke (Cerebrovascular Disease)', 'Childhood Blood Lead Level Screening', 'Childhood Lead Poisoning', 'Gonorrhea in Females', 'Tuberculosis', 'Below Poverty Level', 'Crowded Housing', 'Dependency', 'No High School Diploma', 'Per Capita Income', 'Unemployment', 'OV65', 'neighborhood_id', 'accessible', 'activities', 'african', 'airport', 'amazing', 'american', 'aquarium', 'architecture', 'art', 'artists', 'arts', 'authentic', 'award', 'awesome', 'bakeries', 'bar', 'bars', 'baseball', 'beach', 'beaches', 'beautiful', 'beer', 'big', 'bike', 'biking', 'blend', 'blue', 'blues', 'boasts', 'book', 'booming', 'boutique', 'boutiques', 'breakfast', 'breweries', 'brewery', 'brick', 'broadway', 'brown', 'brunch', 'bus', 'buses', 'business', 'businesses', 'bustling', 'cafe', 'cafes', 'campus', 'car', 'casual', 'catch', 'central', 'centrally', 'charming', 'chicken', 'chinatown', 'chinese', 'classic', 'club', 'clubs', 'coast', 'cocktail', 'cocktails', 'coffee', 'collection', 'comedy', 'community_y', 'convenience', 'convenient', 'conveniently', 'cool', 'corridor', 'couple', 'craft', 'creative', 'cta', 'cuisine', 'cultural', 'culture', 'delicious', 'different', 'dining', 'district', 'districts', 'dive', 'diverse', 'diversity', 'division', 'divvy', 'drink', 'drinks', 'drive', 'dynamic', 'easily', 'eat', 'eateries', 'eclectic', 'elevated', 'endless', 'energy', 'enjoy', 'entertainment', 'ethnic', 'events', 'explore', 'exploring', 'families', 'family', 'famous', 'fans', 'fantastic', 'farmers', 'favorite', 'festivals', 'field', 'fitness', 'flat', 'food', 'free', 'fresh', 'friendly', 'fun', 'furnished', 'galleries', 'game', 'gardens', 'gold', 'good', 'green', 'grocery', 'guests', 'heart', 'hip', 'historic', 'historical', 'history', 'home', 'homes', 'hospital', 'hot', 'hottest', 'house', 'houses', 'huge', 'ice', 'iconic', 'incredible', 'independent', 'industry', 'institute', 'italian', 'italy', 'jazz', 'jewel', 'known', 'lakefront', 'lakeview', 'landmark', 'large', 'library', 'life', 'little', 'lively', 'local', 'locally', 'locals', 'love', 'market', 'medical', 'metra', 'mexican', 'michelin', 'millennium', 'mix', 'modern', 'movie', 'museum', 'museums', 'music', 'nature', 'neighbors', 'night', 'nightlife', 'noise', 'office', 'old', 'open', 'outdoor', 'outside', 'parking', 'parks', 'path', 'people', 'perfect', 'pizza', 'places', 'planetarium', 'polish', 'pool', 'popular', 'premier', 'professionals', 'quaint', 'quick', 'quiet', 'rated', 'red', 'renowned', 'residential', 'residents', 'restaurant', 'restaurants', 'retail', 'rich', 'river', 'room', 'running', 'runs', 'rush', 'safe', 'safest', 'scene', 'school', 'science', 'shop', 'shopping', 'shops', 'short', 'sits', 'small', 'soldier', 'space', 'sports', 'star', 'station', 'steps', 'store', 'stores', 'stroll', 'students', 'stunning', 'style', 'subway', 'summer', 'super', 'sushi', 'taste', 'tennis', 'theater', 'theaters', 'theatre', 'thriving', 'tourist', 'tower', 'traffic', 'trail', 'train', 'transit', 'transportation', 'tree', 'trendiest', 'trendy', 'ukrainian', 'unique', 'university', 'upscale', 'urban', 'variety', 'venues', 'vibe', 'vibrant', 'views', 'vintage', 'walkable', 'walking', 'water', 'western', 'white', 'wicker', 'wine', 'winning', 'wonderful', 'work', 'working', 'world', 'young', 'zoo', 'num_listings', 'price_norm', 'Neighborhood', 'ATM', 'Accessories Store', 'Adult Boutique', 'Afghan Restaurant', 'African Restaurant', 'Airport', 'Airport Food Court', 'Airport Lounge', 'Airport Service', 'American Restaurant', 'Amphitheater', 'Antique Shop', 'Aquarium', 'Arcade', 'Argentinian Restaurant', 'Art Gallery', 'Art Museum', 'Arts & Crafts Store', 'Arts & Entertainment', 'Asian Restaurant', 'Athletics & Sports', 'Auto Dealership', 'Automotive Shop', 'BBQ Joint', 'Bagel Shop', 'Bakery', 'Bank', 'Bar', 'Baseball Field', 'Baseball Stadium', 'Basketball Court', 'Beach', 'Bed & Breakfast', 'Beer Bar', 'Beer Garden', 'Beer Store', 'Big Box Store', 'Bike Shop', 'Bistro', 'Bookstore', 'Boutique', 'Bowling Alley', 'Boxing Gym', 'Brazilian Restaurant', 'Breakfast Spot', 'Brewery', 'Bubble Tea Shop', 'Buffet', 'Burger Joint', 'Burrito Place', 'Bus Line', 'Bus Station', 'Butcher', 'Cafeteria', 'CafÃ©', 'Cajun / Creole Restaurant', 'Camera Store', 'Candy Store', 'Caribbean Restaurant', 'Casino', 'Chinese Restaurant', 'Chocolate Shop', 'Circus', 'Climbing Gym', 'Clothing Store', 'Cocktail Bar', 'Coffee Shop', 'College Arts Building', 'College Gym', 'College Quad', 'College Stadium', 'Concert Hall', 'Convenience Store', 'Cosmetics Shop', 'Cuban Restaurant', 'Cultural Center', 'Cupcake Shop', 'Currency Exchange', 'Cycle Studio', 'Czech Restaurant', 'Deli / Bodega', 'Department Store', 'Design Studio', 'Dessert Shop', 'Dim Sum Restaurant', 'Diner', 'Discount Store', 'Distillery', 'Dive Bar', 'Dog Run', 'Donut Shop', 'Dry Cleaner', 'Eastern European Restaurant', 'Electronics Store', 'Ethiopian Restaurant', 'Exhibit', 'Eye Doctor', 'Fabric Shop', 'Falafel Restaurant', 'Farm', 'Farmers Market', 'Fast Food Restaurant', 'Field', 'Filipino Restaurant', 'Fish & Chips Shop', 'Fish Market', 'Flea Market', 'Flower Shop', 'Fondue Restaurant', 'Food', 'Food & Drink Shop', 'Food Court', 'Food Truck', 'Football Stadium', 'Fountain', 'French Restaurant', 'Fried Chicken Joint', 'Frozen Yogurt Shop', 'Fruit & Vegetable Store', 'Furniture / Home Store', 'Gaming Cafe', 'Garden', 'Garden Center', 'Gas Station', 'Gastropub', 'Gay Bar', 'General Entertainment', 'German Restaurant', 'Gift Shop', 'Golf Course', 'Golf Driving Range', 'Gourmet Shop', 'Greek Restaurant', 'Grocery Store', 'Gun Shop', 'Gym', 'Gym / Fitness Center', 'Gym Pool', 'Gymnastics Gym', 'Harbor / Marina', 'Hardware Store', 'Health & Beauty Service', 'Health Food Store', 'Heliport', 'Historic Site', 'History Museum', 'Hobby Shop', 'Hockey Arena', 'Hookah Bar', 'Hostel', 'Hot Dog Joint', 'Hotel', 'Hotel Bar', 'Hotpot Restaurant', 'Ice Cream Shop', 'Indian Restaurant', 'Indie Movie Theater', 'Indonesian Restaurant', 'Indoor Play Area', 'Intersection', 'Irish Pub', 'Israeli Restaurant', 'Italian Restaurant', 'Japanese Restaurant', 'Jazz Club', 'Jewelry Store', 'Juice Bar', 'Karaoke Bar', 'Kids Store', 'Kitchen Supply Store', 'Korean Restaurant', 'Lake', 'Latin American Restaurant', 'Laundromat', 'Laundry Service', 'Library', 'Light Rail Station', 'Lighthouse', 'Lingerie Store', 'Liquor Store', 'Lounge', 'Market', 'Massage Studio', 'Mediterranean Restaurant', "Men's Store", 'Metro Station', 'Mexican Restaurant', 'Middle Eastern Restaurant', 'Military Base', 'Mini Golf', 'Miscellaneous Shop', 'Mobile Phone Shop', 'Molecular Gastronomy Restaurant', 'Motel', 'Motorcycle Shop', 'Movie Theater', 'Multiplex', 'Museum', 'Music School', 'Music Store', 'Music Venue', 'Nail Salon', 'Nature Preserve', 'New American Restaurant', 'Newsstand', 'Nightclub', 'Non-Profit', 'Noodle House', 'North Indian Restaurant', 'Office', 'Optical Shop', 'Organic Grocery', 'Other Great Outdoors', 'Outdoor Sculpture', 'Outdoors & Recreation', 'Outlet Store', 'Pakistani Restaurant', 'Paper / Office Supplies Store', 'Park', 'Parking', 'Pastry Shop', 'Pedestrian Plaza', 'Performing Arts Venue', 'Persian Restaurant', 'Peruvian Restaurant', 'Pet Service', 'Pet Store', 'Pharmacy', 'Pie Shop', 'Pier', 'Pizza Place', 'Playground', 'Plaza', 'Poke Place', 'Polish Restaurant', 'Pool', 'Pool Hall', 'Portuguese Restaurant', 'Post Office', 'Pub', 'Public Art', 'Racetrack', 'Ramen Restaurant', 'Record Shop', 'Recording Studio', 'Recreation Center', 'Recycling Facility', 'Rental Car Location', 'Residential Building (Apartment / Condo)', 'Restaurant', 'Rock Club', 'Roof Deck', 'Salad Place', 'Salon / Barbershop', 'Sandwich Place', 'Sausage Shop', 'Scandinavian Restaurant', 'Scenic Lookout', 'Science Museum', 'Sculpture Garden', 'Seafood Restaurant', 'Shipping Store', 'Shoe Store', 'Shop & Service', 'Shopping Mall', 'Skate Park', 'Skating Rink', 'Smoke Shop', 'Smoothie Shop', 'Snack Place', 'Soccer Field', 'Soccer Stadium', 'South American Restaurant', 'Southern / Soul Food Restaurant', 'Spa', 'Speakeasy', 'Sporting Goods Shop', 'Sports Bar', 'Stadium', 'Steakhouse', 'Storage Facility', 'Student Center', 'Supermarket', 'Supplement Shop', 'Surf Spot', 'Sushi Restaurant', 'Szechuan Restaurant', 'Taco Place', 'Taiwanese Restaurant', 'Tapas Restaurant', 'Tattoo Parlor', 'Tea Room', 'Tennis Court', 'Tex-Mex Restaurant', 'Thai Restaurant', 'Theater', 'Thrift / Vintage Store', 'Tiki Bar', 'Toll Booth', 'Toy / Game Store', 'Track', 'Track Stadium', 'Trail', 'Train Station', 'Turkish Restaurant', 'Ukrainian Restaurant', 'Used Bookstore', 'Vegetarian / Vegan Restaurant', 'Veterinarian', 'Video Game Store', 'Video Store', 'Vietnamese Restaurant', 'Volleyball Court', 'Warehouse', 'Warehouse Store', 'Waterfront', 'Whisky Bar', 'Wine Bar', 'Wine Shop', 'Wings Joint', "Women's Store", 'Yoga Studio']

In [17]:
merged.drop(['Neighborhood','community_x'],axis=1,inplace=True)
merged.shape

In [19]:
# move example neighborhood/neighborhood to beginning
col = merged.pop("neighborhood_id")
merged.insert(0, col.name, col)

In [20]:
merged

,neighborhood_id,shape_area,area_num_1,shape_len,2000_POP,2010_POP,TOT_POP,UND19,A20_34,A35_49,...,Volleyball Court,Warehouse,Warehouse Store,Waterfront,Whisky Bar,Wine Bar,Wine Shop,Wings Joint,Women's Store,Yoga Studio
0,DOUGLAS,4.600462e+07,35,31027.05451,26470,18238,20781,0.212309,0.310813,0.172465,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.020833,0.0,0.000000
1,OAKLAND,1.691396e+07,36,19565.50615,6110,5918,6645,0.333333,0.184349,0.233860,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
2,FULLER PARK,1.991670e+07,37,25339.08975,3420,2876,2439,0.161132,0.193522,0.148421,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.020000,0.0,0.000000
3,GRAND BOULEVARD,4.849250e+07,38,28196.83716,28006,21929,22313,0.264823,0.193251,0.216959,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
4,KENWOOD,2.907174e+07,39,23325.16791,18363,17841,17189,0.184420,0.275816,0.184886,...,0.00,0.000000,0.00,0.01,0.00,0.000000,0.00,0.000000,0.0,0.020000
5,LINCOLN SQUARE,7.135233e+07,4,36624.60308,44574,39493,41715,0.176339,0.321994,0.249982,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.01,0.000000,0.0,0.000000
6,WASHINGTON PARK,4.237388e+07,40,28175.31609,14146,11717,11502,0.372805,0.237872,0.167884,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.000000,0.0,0.000000
7,HYDE PARK,4.510538e+07,41,29746.70820,29920,25681,26827,0.197525,0.365378,0.150520,...,0.00,0.000000,0.00,0.01,0.00,0.000000,0.00,0.000000,0.0,0.020000
8,WOODLAWN,5.781518e+07,42,46936.95924,27086,23740,23268,0.319538,0.224171,0.170664,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.010000
9,ROGERS PARK,5.125990e+07,1,34052.39758,63484,54991,55062,0.211253,0.310850,0.228106,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
10,JEFFERSON PARK,6.486816e+07,11,44011.95717,25859,25448,26808,0.210758,0.198038,0.214003,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.000000,0.0,0.000000
11,FOREST GLEN,8.913089e+07,12,74493.82160,18165,18508,19019,0.265051,0.133708,0.215626,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.010000
12,NORTH PARK,7.028871e+07,13,41581.94865,18514,17931,18842,0.244189,0.209797,0.188833,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.000000,0.0,0.010000
13,ALBANY PARK,5.354223e+07,14,39339.01644,57655,51542,51992,0.255789,0.269868,0.224227,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
14,PORTAGE PARK,1.101961e+08,15,46520.64214,65340,64124,64307,0.228824,0.226725,0.211890,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.000000,0.0,0.000000
15,IRVING PARK,8.961138e+07,16,49083.22409,58643,53359,54606,0.229499,0.256986,0.240706,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
16,DUNNING,1.035950e+08,17,54555.99253,42164,41932,43689,0.232667,0.197098,0.195244,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
17,BELMONT CRAGIN,1.090994e+08,19,43311.70738,78144,78743,79910,0.309035,0.223289,0.218583,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
18,WEST RIDGE,9.842909e+07,2,43020.68946,73199,71942,76215,0.272335,0.223906,0.196825,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.000000,0.0,0.000000
19,HERMOSA,3.260206e+07,20,27179.01744,26908,25010,24144,0.284294,0.258988,0.188370,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
20,AVONDALE,5.529060e+07,21,34261.93340,43083,39262,37368,0.228966,0.328918,0.209993,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.020000,0.0,0.000000
21,LOGAN SQUARE,1.000576e+08,22,49213.42175,82715,72791,73046,0.209293,0.377420,0.227186,...,0.01,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
22,HUMBOLDT PARK,1.004809e+08,23,48583.06433,65836,56323,56427,0.330445,0.246549,0.193719,...,0.00,0.010000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
23,WEST TOWN,1.275629e+08,24,55203.71870,87435,82236,84502,0.160588,0.445563,0.231095,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.000000,0.0,0.000000
24,AUSTIN,1.992542e+08,25,75226.47492,117527,98514,95260,0.278029,0.218119,0.180663,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010638,0.0,0.010638
25,WEST GARFIELD PARK,3.609285e+07,26,26238.54198,23019,18001,17163,0.349240,0.210977,0.170716,...,0.00,0.010204,0.00,0.00,0.00,0.000000,0.00,0.010204,0.0,0.000000
26,EAST GARFIELD PARK,5.388322e+07,27,31514.62596,20881,20567,19996,0.321164,0.240748,0.176885,...,0.00,0.010000,0.00,0.00,0.00,0.010000,0.00,0.010000,0.0,0.000000
27,NEAR WEST SIDE,1.584925e+08,28,53003.59294,46419,54881,62872,0.189226,0.426199,0.204527,...,0.00,0.000000,0.01,0.00,0.00,0.000000,0.00,0.000000,0.0,0.020000
28,NORTH LAWNDALE,8.948742e+07,29,44959.45966,41768,35912,35947,0.324422,0.249951,0.165021,...,0.00,0.000000,0.01,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
29,UPTOWN,6.509564e+07,3,46972.79455,63551,56362,57973,0.128163,0.342522,0.228348,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.01,0.000000,0.0,0.010000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,CALUMET HEIGHTS,4.882624e+07,48,32925.36587,15974,13812,13188,0.163861,0.153776,0.188960,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.020000,0.0,0.000000
44,ROSELAND,1.343137e+08,49,56632.79543,52723,44619,42433,0.269012,0.180166,0.180803,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.020000,0.0,0.000000
45,NORTH CENTER,5.705417e+07,5,31391.66975,31895,31867,35789,0.247143,0.276677,0.271284,...,0.00,0.000000,0.00,0.00,0.00,0.010000,0.00,0.000000,0.0,0.010000
46,PULLMAN,5.900156e+07,50,35572.06951,8921,7325,6613,0.210948,0.208680,0.212460,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.030000,0.0,0.000000
47,SOUTH DEERING,3.037971e+08,51,80389.87180,16990,15109,14614,0.295333,0.166210,0.188655,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.030000,0.0,0.000000
48,RIVERDALE,9.838950e+07,54,46455.44086,9809,6482,7394,0.464431,0.248445,0.127536,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.000000,0.0,0.000000
49,HEGEWISCH,1.459657e+08,55,73692.38213,9781,9426,9418,0.236887,0.195158,0.169144,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
50,GARFIELD RIDGE,1.178908e+08,56,60080.44797,36101,34513,36396,0.253682,0.190900,0.211314,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
51,ARCHER HEIGHTS,5.592251e+07,57,31880.02103,12644,13393,13142,0.305661,0.215112,0.222569,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
52,BRIGHTON PARK,7.589279e+07,58,36537.13431,44912,45368,44813,0.332404,0.227858,0.217348,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
53,BRIDGEPORT,5.829152e+07,60,32732.71833,33694,31977,33637,0.203080,0.268960,0.193923,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.020000,0.0,0.000000
54,NEW CITY,1.346370e+08,61,48133.59596,51721,44377,39561,0.327065,0.230935,0.189151,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
55,WEST ELSDON,3.271109e+07,62,26229.69560,15921,18109,19237,0.324999,0.228934,0.212507,...,0.00,0.000000,0.00,0.00,0.00,0.010000,0.00,0.020000,0.0,0.000000
56,GAGE PARK,6.128490e+07,63,32294.19591,39193,39894,40873,0.355687,0.249529,0.206224,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.020000,0.0,0.000000
57,CLEARING,7.114519e+07,64,45363.28617,22331,23139,25891,0.269437,0.216446,0.215249,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.000000,0.0,0.000000
58,WEST LAWN,8.231530e+07,65,41934.49013,29235,33355,33108,0.334270,0.227588,0.211127,...,0.00,0.000000,0.01,0.00,0.00,0.010000,0.00,0.000000,0.0,0.000000
59,CHICAGO LAWN,9.827947e+07,66,40073.09984,61412,55628,53098,0.313741,0.237768,0.198783,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
60,WEST ENGLEWOOD,8.794769e+07,67,40195.20331,45282,35505,29929,0.270741,0.201443,0.179826,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.020000,0.0,0.000000
61,ENGLEWOOD,8.565232e+07,68,42316.84430,40222,30654,25075,0.310030,0.238166,0.140459,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
62,GREATER GRAND CROSSING,9.885317e+07,69,54645.33030,38619,32602,31766,0.270887,0.221495,0.176258,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010204,0.0,0.000000
63,LINCOLN PARK,8.831640e+07,7,49478.42777,64320,64116,67710,0.177330,0.443775,0.169266,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.000000,0.0,0.010000
64,ASHBURN,1.354603e+08,70,54818.15463,39584,41081,43792,0.296835,0.191291,0.210084,...,0.00,0.000000,0.02,0.00,0.00,0.000000,0.00,0.000000,0.0,0.000000
65,AUBURN GRESHAM,1.050654e+08,71,46757.72172,55928,48743,46278,0.252733,0.198280,0.170081,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
66,BEVERLY,8.877936e+07,72,44591.48510,21992,20034,20822,0.256988,0.137259,0.205312,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.000000,0.0,0.000000
67,WASHINGTON HEIGHTS,7.963575e+07,73,42222.59816,29843,26493,27453,0.227225,0.194879,0.174626,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.010000,0.0,0.000000
68,MOUNT GREENWOOD,7.558429e+07,74,48665.13054,18820,19093,19277,0.277377,0.197074,0.198734,...,0.00,0.000000,0.01,0.00,0.00,0.000000,0.00,0.000000,0.0,0.000000
69,MORGAN PARK,9.187734e+07,75,46396.41936,25226,22544,22394,0.263017,0.159462,0.167322,...,0.00,0.000000,0.00,0.00,0.00,0.000000,0.00,0.000000,0.0,0.000000
70,OHARE,3.718356e+08,76,173625.98470,11665,12756,12377,0.168458,0.266624,0.237941,...,0.00,0.000000,0.00,0.00,0.00,0.014925,0.00,0.000000,0.0,0.014925
71,EDGEWATER,4.844999e+07,77,31004.83095,62198,56521,55965,0.142142,0.290003,0.223265,...,0.00,0.000000,0.00,0.00,0.01,0.010000,0.02,0.000000,0.0,0.000000
72,EDISON PARK,3.163631e+07,9,25937.22684,11328,11187,11605,0.231710,0.201034,0.228867,...,0.00,0.000000,0.01,0.00,0.00,0.000000,0.00,0.000000,0.0,0.010000

In [29]:
merged.columns[111]

'accessible'

In [30]:
merged.columns[272]

'little'

In [53]:
merged.columns[628]

'AdultCareFacilities'

- merged[0:2] are neighborhood IDs/names
- merged[2:216] are qualitative features
- merged[216:628] are foursquare features
- merged[628:] are quantitative features

# Write Output File

In [54]:
merged.to_csv('cleaned_data/merged.csv',index=False)