In [1]:
import pandas as pd

# Read Quantitative Data

In [2]:
df = pd.read_csv('cleaned_data/quant_features.csv')
df.head()

,Unique Identifier,AdultCareFacilities,Clinics,CommunityHealthCenters,DiagnosticTreatmentCenters,Hospitals,NursingHomes,SchoolBasedHealthFacilities,Daycares,TotalPop,...,DrugHospPopPercent,PsychHospPopPercent,StrokeHospPopPercent,HIVPopPercent,HepBPopPercent,HepCPopPercent,TBPopPercent,GonorrheaPopPercent,SyphilisPopPercent,PrematureMortalityPopPercent
0,1,2,1,0,4,0,7,0,95,69435,...,1.063443,0.676279,0.349523,0.028723,0.06609,0.106615,0.005771,0.184327,0.034544,0.181910
1,2,0,0,0,0,0,0,0,8,25602,...,0.519000,0.522500,0.287600,0.000000,0.01240,0.042500,0.003900,0.000000,0.000000,0.140000
2,3,0,3,0,4,1,1,1,86,106244,...,0.402325,0.462069,0.282341,0.041906,0.04860,0.071517,0.008766,0.185412,0.054593,0.134602
3,4,0,1,0,1,0,1,0,23,32002,...,0.296500,0.314500,0.261000,0.000000,0.19090,0.087900,0.014600,0.021900,0.000000,0.126400
4,5,0,0,0,2,1,0,0,39,42485,...,0.381600,0.330400,0.272800,0.028700,0.05840,0.062700,0.003900,0.162400,0.044700,0.079200

In [4]:
df.shape

(146, 55)

# Read Qualitative Data

In [5]:
df2 = pd.read_csv('cleaned_data/airbnb.csv')
df2.head()

,neighborhood_id,accessible,airport,amazing,american,anywhere,architecture,art,artists,authentic,...,waterfront,well,wine,wonderful,world,young,zoo,neighborhood,num_listings,price_norm
0,1,0.035714,0.017857,0.017857,0.000000,0.017857,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.232143,0.000000,0.000000,0.035714,0.000000,0.428571,Allerton,77,31.006370
1,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Arden Heights,5,28.170000
2,3,0.008475,0.042373,0.110169,0.037288,0.008475,0.003390,0.020339,0.011864,0.032203,...,0.013559,0.147458,0.018644,0.057627,0.100000,0.076271,0.003390,Astoria,919,59.324403
3,4,0.052632,0.052632,0.052632,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.052632,0.000000,0.000000,Bath Beach,27,40.018519
4,5,0.003311,0.029801,0.024834,0.048013,0.006623,0.019868,0.001656,0.000000,0.026490,...,0.026490,0.092715,0.009934,0.008278,0.240066,0.004967,0.000000,Financial District,832,84.430094

In [6]:
df2.shape

(145, 218)

In [7]:
df3 = pd.read_csv('cleaned_data/foursquare.csv')
df3.head()

,Neighborhood,Accessories Store,Afghan Restaurant,African Restaurant,Airport,Airport Food Court,Airport Lounge,Airport Service,Airport Terminal,American Restaurant,...,Waterfront,Weight Loss Center,Whisky Bar,Wine Bar,Wine Shop,Wings Joint,Women's Store,Yoga Studio,Zoo,Zoo Exhibit
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.01,...,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
1,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.01,...,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
2,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.02,...,0.0,0.0,0.0,0.0,0.01,0.0,0.00,0.0,0.0,0.0
3,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.02,...,0.0,0.0,0.0,0.0,0.00,0.0,0.01,0.0,0.0,0.0

# Merge Datasets on Unique Identifier

In [8]:
merged = pd.merge(df,df2,left_on='Unique Identifier', right_on = 'neighborhood_id')
merged = pd.merge(merged,df3,left_on='neighborhood_id', right_on = 'Neighborhood')
merged.head()

,Unique Identifier,AdultCareFacilities,Clinics,CommunityHealthCenters,DiagnosticTreatmentCenters,Hospitals,NursingHomes,SchoolBasedHealthFacilities,Daycares,TotalPop,...,Waterfront,Weight Loss Center,Whisky Bar,Wine Bar,Wine Shop,Wings Joint,Women's Store,Yoga Studio,Zoo,Zoo Exhibit
0,1,2,1,0,4,0,7,0,95,69435,...,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
1,2,0,0,0,0,0,0,0,8,25602,...,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
2,3,0,3,0,4,1,1,1,86,106244,...,0.0,0.0,0.0,0.0,0.01,0.0,0.00,0.0,0.0,0.0
3,4,0,1,0,1,0,1,0,23,32002,...,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0
4,5,0,0,0,2,1,0,0,39,42485,...,0.0,0.0,0.0,0.0,0.00,0.0,0.01,0.0,0.0,0.0

In [9]:
merged.shape

(140, 686)

# Drop Duplicate Column and Split Qualitative/Quantitative Features

In [10]:
print(merged.columns.tolist())

['Unique Identifier', 'AdultCareFacilities', 'Clinics', 'CommunityHealthCenters', 'DiagnosticTreatmentCenters', 'Hospitals', 'NursingHomes', 'SchoolBasedHealthFacilities', 'Daycares', 'TotalPop', 'shape_area', 'rating_b', 'FemalePopPercent', 'PopU18PopPercent', 'Pop18t24PopPercent', 'Pop25t44PopPercent', 'Pop45t64PopPercent', 'Pop65plPopPercent', 'HispanicPopPercent', 'WhiteNonHispPopPercent', 'BlackNonHispPopPercent', 'AsianPIPopPercent', 'OtherRacePopPercent', 'ForeignBornPopPercent', 'LimitedEngPopPercent', 'EduLessThanHSPopPercent', 'PovertyPopPercent', 'FoodStampSNAPPopPercent', 'UnemploymentPopPercent', 'DisabilityPopPercent', 'DisabilityVisionPopPercent', 'DisabilityCognitivePopPercent', 'DisabilityAmbulatoryPopPercent', 'DisabilitySelfCarePopPercent', 'DisabilityIndepLivPopPercent', 'HealthInsPopPercent', 'MedicaidEnrollPopPercent', 'AlcoholRetailersPopPercent', 'TobaccoRetailersPopPercent', 'FelonyCrimePopPercent', 'PropertyCrimePopPercent', 'ViolentCrimePopPercent', 'JailIncarcerationPopPercent', 'AssaultHospPopPercent', 'AlcoholHospPopPercent', 'DrugHospPopPercent', 'PsychHospPopPercent', 'StrokeHospPopPercent', 'HIVPopPercent', 'HepBPopPercent', 'HepCPopPercent', 'TBPopPercent', 'GonorrheaPopPercent', 'SyphilisPopPercent', 'PrematureMortalityPopPercent', 'neighborhood_id', 'accessible', 'airport', 'amazing', 'american', 'anywhere', 'architecture', 'art', 'artists', 'authentic', 'available', 'awesome', 'bakery', 'banks', 'bar', 'barclays', 'bars', 'beautiful', 'beer', 'big', 'bike', 'botanical', 'boutiques', 'bridge', 'brownstones', 'brunch', 'buildings', 'bus', 'buses', 'bustling', 'cafe', 'cafes', 'called', 'caribbean', 'charming', 'chinese', 'circle', 'class', 'clubs', 'coffee', 'columbus', 'come', 'community', 'convenience', 'convenient', 'conveniently', 'cool', 'corner', 'couple', 'cuisine', 'cultural', 'culture', 'cute', 'deli', 'delicious', 'delis', 'different', 'dining', 'diverse', 'diversity', 'door', 'drink', 'easily', 'eat', 'eateries', 'enjoy', 'entertainment', 'every', 'experience', 'explore', 'express', 'families', 'family', 'famous', 'fantastic', 'fast', 'favorite', 'filled', 'five', 'food', 'free', 'friendly', 'front', 'fun', 'galleries', 'garden', 'good', 'green', 'groceries', 'grocery', 'guests', 'hall', 'happy', 'heart', 'hip', 'historic', 'historical', 'history', 'home', 'hotel', 'house', 'iconic', 'include', 'indian', 'italian', 'jazz', 'known', 'large', 'late', 'laundromat', 'laundry', 'library', 'life', 'lines', 'live', 'lively', 'living', 'local', 'looking', 'love', 'lovely', 'mall', 'market', 'markets', 'metropolitan', 'mexican', 'mile', 'mix', 'movie', 'museum', 'museums', 'music', 'name', 'natural', 'neighbors', 'nice', 'night', 'nightlife', 'old', 'open', 'options', 'organic', 'outdoor', 'outside', 'parking', 'parks', 'peaceful', 'people', 'perfect', 'pharmacy', 'pizza', 'places', 'plaza', 'popular', 'professionals', 'proximity', 'quick', 'quiet', 'real', 'residential', 'residents', 'restaurant', 'restaurants', 'ride', 'river', 'riverside', 'safe', 'scene', 'shop', 'shopping', 'shops', 'short', 'small', 'space', 'spots', 'station', 'stay', 'steps', 'stops', 'store', 'stores', 'stroll', 'subway', 'summer', 'super', 'supermarket', 'supermarkets', 'thai', 'theaters', 'theatre', 'three', 'time', 'train', 'trains', 'transportation', 'tree', 'trendy', 'unique', 'us', 'variety', 'venues', 'vibe', 'vibrant', 'view', 'views', 'vintage', 'visit', 'walking', 'waterfront', 'well', 'wine', 'wonderful', 'world', 'young', 'zoo', 'neighborhood', 'num_listings', 'price_norm', 'Neighborhood', 'Accessories Store', 'Afghan Restaurant', 'African Restaurant', 'Airport', 'Airport Food Court', 'Airport Lounge', 'Airport Service', 'Airport Terminal', 'American Restaurant', 'Amphitheater', 'Animal Shelter', 'Antique Shop', 'Aquarium', 'Arcade', 'Arepa Restaurant', 'Argentinian Restaurant', 'Art Gallery', 'Art Museum', 'Arts & Crafts Store', 'Arts & Entertainment', 'Asian Restaurant', 'Athletics & Sports', 'Australian Restaurant', 'Austrian Restaurant', 'Auto Dealership', 'Auto Garage', 'Auto Workshop', 'Automotive Shop', 'BBQ Joint', 'Baby Store', 'Bagel Shop', 'Bakery', 'Bank', 'Bar', 'Baseball Field', 'Baseball Stadium', 'Basketball Court', 'Basketball Stadium', 'Bath House', 'Beach', 'Beach Bar', 'Beer Bar', 'Beer Garden', 'Beer Store', 'Big Box Store', 'Bike Rental / Bike Share', 'Bike Trail', 'Bistro', 'Board Shop', 'Boat or Ferry', 'Bookstore', 'Botanical Garden', 'Boutique', 'Bowling Alley', 'Boxing Gym', 'Brazilian Restaurant', 'Breakfast Spot', 'Brewery', 'Bridge', 'Bubble Tea Shop', 'Buffet', 'Building', 'Burger Joint', 'Burrito Place', 'Bus Line', 'Bus Station', 'Bus Stop', 'Butcher', 'Cafeteria', 'CafÃ©', 'Cajun / Creole Restaurant', 'Campground', 'Candy Store', 'Cantonese Restaurant', 'Car Wash', 'Caribbean Restaurant', 'Casino', 'Caucasian Restaurant', 'Cemetery', 'Check Cashing Service', 'Cheese Shop', 'Chinese Restaurant', 'Chocolate Shop', 'Church', 'Climbing Gym', 'Clothing Store', 'Cocktail Bar', 'Coffee Shop', 'College Academic Building', 'College Basketball Court', 'College Gym', 'College Theater', 'Colombian Restaurant', 'Comedy Club', 'Comfort Food Restaurant', 'Comic Shop', 'Concert Hall', 'Construction & Landscaping', 'Convenience Store', 'Cosmetics Shop', 'Coworking Space', 'Creperie', 'Cuban Restaurant', 'Cultural Center', 'Cupcake Shop', 'Cycle Studio', 'Dance Studio', 'Deli / Bodega', 'Department Store', 'Dessert Shop', 'Dim Sum Restaurant', 'Diner', 'Discount Store', 'Distillery', 'Dive Bar', "Doctor's Office", 'Dog Run', 'Donut Shop', 'Dosa Place', 'Drugstore', 'Dry Cleaner', 'Dumpling Restaurant', 'Duty-free Shop', 'Eastern European Restaurant', 'Electronics Store', 'Empanada Restaurant', 'English Restaurant', 'Ethiopian Restaurant', 'Event Service', 'Event Space', 'Exhibit', 'Falafel Restaurant', 'Farm', 'Farmers Market', 'Fast Food Restaurant', 'Field', 'Filipino Restaurant', 'Film Studio', 'Financial or Legal Service', 'Fish & Chips Shop', 'Fish Market', 'Flea Market', 'Flower Shop', 'Food', 'Food & Drink Shop', 'Food Court', 'Food Service', 'Food Truck', 'Fountain', 'French Restaurant', 'Fried Chicken Joint', 'Frozen Yogurt Shop', 'Fruit & Vegetable Store', 'Furniture / Home Store', 'Gaming Cafe', 'Garden', 'Garden Center', 'Gas Station', 'Gastropub', 'Gay Bar', 'General Entertainment', 'German Restaurant', 'Gift Shop', 'Go Kart Track', 'Golf Course', 'Golf Driving Range', 'Gourmet Shop', 'Government Building', 'Greek Restaurant', 'Grocery Store', 'Gym', 'Gym / Fitness Center', 'Gym Pool', 'Gymnastics Gym', 'Halal Restaurant', 'Harbor / Marina', 'Hardware Store', 'Hawaiian Restaurant', 'Health & Beauty Service', 'Health Food Store', 'Heliport', 'High School', 'Himalayan Restaurant', 'Historic Site', 'History Museum', 'Hobby Shop', 'Home Service', 'Hookah Bar', 'Hot Dog Joint', 'Hotel', 'Hotel Bar', 'Hotpot Restaurant', 'Ice Cream Shop', 'Indian Restaurant', 'Indie Movie Theater', 'Indie Theater', 'Indonesian Restaurant', 'Indoor Play Area', 'Industrial Estate', 'Intersection', 'Irish Pub', 'Israeli Restaurant', 'Italian Restaurant', 'Japanese Restaurant', 'Jazz Club', 'Jewelry Store', 'Jewish Restaurant', 'Juice Bar', 'Karaoke Bar', 'Kebab Restaurant', 'Kids Store', 'Kitchen Supply Store', 'Korean Restaurant', 'Kosher Restaurant', 'Lake', 'Latin American Restaurant', 'Laundromat', 'Laundry Service', 'Lebanese Restaurant', 'Library', 'Lighthouse', 'Lingerie Store', 'Liquor Store', 'Lounge', 'Luggage Store', 'Mac & Cheese Joint', 'Malay Restaurant', 'Market', 'Martial Arts Dojo', 'Massage Studio', 'Mattress Store', 'Mediterranean Restaurant', 'Memorial Site', "Men's Store", 'Metro Station', 'Mexican Restaurant', 'Middle Eastern Restaurant', 'Mini Golf', 'Miscellaneous Shop', 'Mobile Phone Shop', 'Modern Greek Restaurant', 'Monument / Landmark', 'Moroccan Restaurant', 'Motel', 'Motorcycle Shop', 'Movie Theater', 'Moving Target', 'Multiplex', 'Museum', 'Music School', 'Music Store', 'Music Venue', 'Nail Salon', 'National Park', 'New American Restaurant', 'Night Market', 'Nightclub', 'Nightlife Spot', 'Non-Profit', 'Noodle House', 'Office', 'Opera House', 'Optical Shop', 'Organic Grocery', 'Other Great Outdoors', 'Other Nightlife', 'Outdoor Sculpture', 'Outdoors & Recreation', 'Paella Restaurant', 'Pakistani Restaurant', 'Paper / Office Supplies Store', 'Park', 'Parking', 'Pedestrian Plaza', 'Peking Duck Restaurant', 'Performing Arts Venue', 'Persian Restaurant', 'Peruvian Restaurant', 'Pet CafÃ©', 'Pet Service', 'Pet Store', 'Pharmacy', 'Piano Bar', 'Pie Shop', 'Pier', 'Pilates Studio', 'Pizza Place', 'Planetarium', 'Platform', 'Playground', 'Plaza', 'Poke Place', 'Polish Restaurant', 'Pool', 'Pool Hall', 'Portuguese Restaurant', 'Pub', 'Public Art', 'Racetrack', 'Ramen Restaurant', 'Record Shop', 'Recording Studio', 'Recreation Center', 'Rental Car Location', 'Rental Service', 'Residential Building (Apartment / Condo)', 'Resort', 'Rest Area', 'Restaurant', 'River', 'Rock Club', 'Roller Rink', 'Roof Deck', 'Russian Restaurant', 'Sake Bar', 'Salad Place', 'Salon / Barbershop', 'Sandwich Place', 'Scandinavian Restaurant', 'Scenic Lookout', 'School', 'Science Museum', 'Sculpture Garden', 'Seafood Restaurant', 'Shanghai Restaurant', 'Shipping Store', 'Shoe Store', 'Shop & Service', 'Shopping Mall', 'Shopping Plaza', 'Skate Park', 'Skating Rink', 'Smoke Shop', 'Smoothie Shop', 'Snack Place', 'Soba Restaurant', 'Soccer Field', 'Social Club', 'Soup Place', 'South American Restaurant', 'South Indian Restaurant', 'Southern / Soul Food Restaurant', 'Souvenir Shop', 'Souvlaki Shop', 'Spa', 'Spanish Restaurant', 'Speakeasy', 'Sporting Goods Shop', 'Sports Bar', 'Sports Club', 'Sri Lankan Restaurant', 'Stables', 'State / Provincial Park', 'Stationery Store', 'Steakhouse', 'Storage Facility', 'Street Food Gathering', 'Supermarket', 'Supplement Shop', 'Surf Spot', 'Sushi Restaurant', 'Swiss Restaurant', 'Szechuan Restaurant', 'Taco Place', 'Taiwanese Restaurant', 'Tanning Salon', 'Tapas Restaurant', 'Tattoo Parlor', 'Tea Room', 'Tech Startup', 'Tennis Court', 'Tennis Stadium', 'Tex-Mex Restaurant', 'Thai Restaurant', 'Theater', 'Theme Park', 'Theme Park Ride / Attraction', 'Theme Restaurant', 'Thrift / Vintage Store', 'Tibetan Restaurant', 'Tiki Bar', 'Toll Plaza', 'Tourist Information Center', 'Toy / Game Store', 'Track', 'Track Stadium', 'Trail', 'Train Station', 'Tram Station', 'Turkish Restaurant', 'Udon Restaurant', 'Ukrainian Restaurant', 'Vape Store', 'Varenyky restaurant', 'Vegetarian / Vegan Restaurant', 'Venezuelan Restaurant', 'Veterinarian', 'Video Game Store', 'Video Store', 'Vietnamese Restaurant', 'Volleyball Court', 'Warehouse Store', 'Waterfront', 'Weight Loss Center', 'Whisky Bar', 'Wine Bar', 'Wine Shop', 'Wings Joint', "Women's Store", 'Yoga Studio', 'Zoo', 'Zoo Exhibit']

In [11]:
merged.drop(['Neighborhood','Unique Identifier'],axis=1,inplace=True)
merged.shape

(140, 684)

In [12]:
# move example neighborhood/neighborhood to beginning
col = merged.pop("neighborhood_id")
merged.insert(0, col.name, col)
col = merged.pop("neighborhood")
merged.insert(1, col.name, col)

In [13]:
merged

,neighborhood_id,neighborhood,AdultCareFacilities,Clinics,CommunityHealthCenters,DiagnosticTreatmentCenters,Hospitals,NursingHomes,SchoolBasedHealthFacilities,Daycares,...,Waterfront,Weight Loss Center,Whisky Bar,Wine Bar,Wine Shop,Wings Joint,Women's Store,Yoga Studio,Zoo,Zoo Exhibit
0,1,Allerton,2,1,0,4,0,7,0,95,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
1,2,Arden Heights,0,0,0,0,0,0,0,8,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
2,3,Astoria,0,3,0,4,1,1,1,86,...,0.00,0.00,0.00,0.00,0.010000,0.000000,0.00,0.00,0.00,0.00
3,4,Bath Beach,0,1,0,1,0,1,0,23,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
4,5,Financial District,0,0,0,2,1,0,0,39,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.01,0.00,0.00,0.00
5,6,Bay Terrace,0,0,0,0,0,0,0,7,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
6,7,Bayside,0,0,0,4,0,2,0,50,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.01,0.00,0.00
7,8,Far Rockaway,5,3,0,3,1,8,2,93,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
8,9,Bedford-Stuyvesant,0,2,1,6,0,1,3,202,...,0.00,0.00,0.00,0.00,0.020000,0.000000,0.00,0.00,0.00,0.00
9,10,Bellerose,0,1,0,0,0,0,0,13,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.01,0.00,0.00
10,11,Belmont,0,1,0,2,0,0,2,50,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.06,0.07
11,12,Bensonhurst,1,2,0,1,0,2,0,51,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
12,13,Borough Park,1,3,0,1,1,2,6,187,...,0.00,0.00,0.00,0.00,0.010000,0.000000,0.00,0.00,0.00,0.00
13,14,Belle Harbor,5,0,0,1,0,3,0,20,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
14,15,Briarwood,0,0,0,1,0,3,0,39,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
15,16,Brighton Beach,0,0,0,1,1,1,1,45,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
16,17,Brooklyn Heights,0,0,0,4,0,0,0,21,...,0.00,0.00,0.00,0.00,0.010000,0.000000,0.00,0.02,0.00,0.00
17,18,Brownsville,0,1,1,4,0,0,0,127,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
18,19,Bushwick,1,6,0,4,2,1,3,161,...,0.00,0.00,0.00,0.00,0.020000,0.000000,0.00,0.00,0.00,0.00
19,20,Cambria Heights,0,0,0,0,0,0,1,32,...,0.00,0.00,0.00,0.00,0.000000,0.010000,0.00,0.00,0.00,0.00
20,21,Canarsie,2,2,0,3,0,2,0,170,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
21,22,Clason Point,0,2,1,2,0,1,1,99,...,0.00,0.00,0.00,0.00,0.010000,0.000000,0.02,0.00,0.00,0.00
22,23,Castleton Corners,0,0,0,1,0,0,0,9,...,0.00,0.00,0.00,0.00,0.000000,0.010000,0.00,0.00,0.01,0.00
23,24,Tottenville,0,0,0,0,0,0,0,15,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
24,25,Chelsea,1,3,2,12,0,0,3,53,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
25,26,Emerson Hill,0,1,0,2,0,2,0,34,...,0.00,0.00,0.00,0.00,0.000000,0.010000,0.00,0.00,0.00,0.00
26,27,Chinatown,0,2,0,6,0,0,2,68,...,0.00,0.00,0.00,0.03,0.000000,0.000000,0.00,0.00,0.00,0.00
27,28,City Island,0,1,0,0,0,1,0,30,...,0.00,0.00,0.00,0.00,0.010000,0.000000,0.00,0.00,0.00,0.00
28,29,Claremont Village,0,2,0,7,0,1,3,103,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.01,0.02
29,30,Clinton Hill,0,0,0,2,0,0,2,43,...,0.00,0.00,0.00,0.00,0.020000,0.000000,0.00,0.02,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,116,Richmondtown,0,0,0,0,0,0,0,10,...,0.00,0.00,0.00,0.00,0.000000,0.010000,0.00,0.00,0.00,0.00
111,117,Ridgewood,0,1,0,2,0,0,0,47,...,0.00,0.01,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
112,118,Rockaway Beach,1,0,1,1,0,6,0,66,...,0.00,0.00,0.00,0.01,0.000000,0.000000,0.00,0.00,0.00,0.00
113,120,Woodrow,0,0,0,0,0,0,0,8,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
114,121,Sea Gate,3,1,0,2,0,3,0,27,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
115,122,Soundview,0,1,0,1,0,1,0,81,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.02,0.00,0.00,0.00
116,123,South Ozone Park,0,1,0,0,0,0,1,90,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
117,124,Springfield Gardens,0,0,0,0,0,0,1,78,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
118,125,St. Albans,0,1,0,1,0,1,0,109,...,0.00,0.00,0.00,0.00,0.000000,0.010000,0.00,0.00,0.00,0.00
119,126,Shore Acres,0,1,0,0,0,2,0,34,...,0.00,0.00,0.00,0.00,0.000000,0.010000,0.00,0.00,0.00,0.00
120,127,Stuyvesant Town,0,0,0,0,0,0,0,5,...,0.00,0.00,0.00,0.01,0.020000,0.000000,0.00,0.00,0.00,0.00
121,128,Sunnyside,1,1,0,2,0,1,0,59,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.01,0.00,0.00
122,129,Sunset Park,0,10,5,8,1,1,8,128,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
123,130,Throgs Neck,0,0,0,1,0,2,0,62,...,0.00,0.00,0.00,0.00,0.010526,0.000000,0.00,0.00,0.00,0.00
124,131,Tremont,0,6,0,4,1,1,0,158,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.08,0.07
125,132,Little Italy,0,0,1,7,0,0,0,41,...,0.00,0.00,0.02,0.03,0.010000,0.000000,0.01,0.03,0.00,0.00
126,133,Unionport,0,0,0,2,0,1,1,39,...,0.00,0.00,0.00,0.00,0.010000,0.000000,0.01,0.00,0.00,0.00
127,134,University Heights,0,0,0,8,0,0,4,184,...,0.00,0.00,0.00,0.00,0.000000,0.010417,0.00,0.00,0.00,0.00
128,135,Upper East Side,4,14,0,11,4,3,2,132,...,0.00,0.00,0.00,0.00,0.020000,0.000000,0.00,0.03,0.00,0.00
129,136,Upper West Side,2,0,1,7,1,2,3,147,...,0.01,0.00,0.00,0.00,0.000000,0.000000,0.00,0.01,0.00,0.00
130,137,Woodlawn,0,2,0,2,0,0,0,54,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
131,138,Washington Heights,0,6,0,11,2,3,7,311,...,0.00,0.00,0.00,0.00,0.020000,0.000000,0.00,0.00,0.00,0.00
132,139,West Brighton,1,2,0,2,1,2,1,24,...,0.00,0.00,0.00,0.00,0.000000,0.010000,0.00,0.00,0.01,0.00
133,140,West Village,0,1,0,6,0,1,0,33,...,0.00,0.00,0.01,0.01,0.000000,0.000000,0.00,0.01,0.00,0.00
134,141,Westchester Square,0,1,0,0,0,0,0,50,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
135,142,Whitestone,0,0,0,0,0,1,0,25,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
136,143,Williamsbridge,2,2,0,0,1,2,1,137,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00
137,144,Williamsburg,1,3,2,7,0,1,2,128,...,0.00,0.00,0.01,0.03,0.010000,0.000000,0.00,0.02,0.00,0.00
138,145,Windsor Terrace,0,0,0,0,0,0,0,32,...,0.00,0.00,0.00,0.01,0.020000,0.000000,0.00,0.00,0.00,0.00
139,146,Woodhaven,0,1,0,0,0,0,0,54,...,0.00,0.00,0.00,0.00,0.000000,0.000000,0.00,0.00,0.00,0.00

In [18]:
merged.columns[56]

'accessible'

In [24]:
merged.columns[272]

'Accessories Store'

- merged[0:2] are neighborhood IDs/names
- merged[2:56] are quantitative features
- merged[56:272] are airbnb features
- merged[272:] are foursquare features

# Write Output File

In [25]:
merged.to_csv('cleaned_data/merged.csv',index=False)